#!/bin/sh
chmod 755 gcc
chmod 755 end
history -c
git config --global user.email "ep16018-2991@sti.chubu.ac.jp"
git config --global user.name "hhhhh"
git add .
git commit -m "new"

expect -c"
git push origin master
expect\"Username for 'https://github.com':\"
send\"okuilab-is\n\"
expect\"Password for 'https://github.com': \"
send\"4wKdkP6y\n\"
interact
"

